/*
 * TomiSoft Product Database Api
 *
 * This document describes the API provided by the TomiSoft.ProductCatalog.Server microservice. This microservice provides information about products, based on barcode.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: sinkutamas@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Attributes;
using Microsoft.AspNetCore.Authorization;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Models;

namespace TomiSoft.ProductCatalog.Server.OpenApiGenerated.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CategoryApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Gets information about every category</remarks>
        /// <param name="acceptLanguage">A list of the languages that the client accepts, as defined in RFC-7231, section 5.3.5. If not provided, or the server does not support any of the requested languages, the content will be returned in the server&#39;s default language. The operation with ID &#39;GetSupportedLanguages&#39; provides you all the languages supported by the server.</param>
        /// <response code="200">The server successfully fulfilled the request and returned all the available categories&#39; information</response>
        /// <response code="204">The request succeeded but there are no categories specified.</response>
        /// <response code="500">Server error occurred</response>
        [HttpGet]
        [Route("/Category")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<CategoryInfoWithProductCountDto>))]
        [ProducesResponseType(statusCode: 500, type: typeof(ErrorResultDto))]
        public abstract Task<IActionResult> GetAllCategories([FromHeader]string acceptLanguage);
    }
}
