/*
 * TomiSoft Product Database Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Attributes;
using Microsoft.AspNetCore.Authorization;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Models;

namespace TomiSoft.ProductCatalog.Server.OpenApiGenerated.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ProductApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Gets a product by barcode</remarks>
        /// <param name="barcode"></param>
        /// <response code="200">A product has been found with the given barcode</response>
        /// <response code="404">No products were found with the given barcode</response>
        /// <response code="500">Server error occurred</response>
        [HttpGet]
        [Route("/Product/{barcode}")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(ProductInformationDto))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResultDto))]
        [ProducesResponseType(statusCode: 500, type: typeof(ErrorResultDto))]
        public abstract Task<IActionResult> GetByBarcode([FromRoute][Required]string barcode);
    }
}
