/*
 * TomiSoft Product Database Api
 *
 * This document describes the API provided by the TomiSoft.ProductCatalog.Server microservice. This microservice provides information about products, based on barcode.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: sinkutamas@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Converters;

namespace TomiSoft.ProductCatalog.Server.OpenApiGenerated.Models
{ 
    /// <summary>
    /// Provides information about a category
    /// </summary>
    [DataContract]
    public class CategoryInfoWithProductCountDto : IEquatable<CategoryInfoWithProductCountDto>
    {
        /// <summary>
        /// The unique ID of the category
        /// </summary>
        /// <value>The unique ID of the category</value>
        [DataMember(Name="CategoryId", EmitDefaultValue=false)]
        public long CategoryId { get; set; }

        /// <summary>
        /// The unique ID of the category.
        /// </summary>
        /// <value>The unique ID of the category.</value>
        [DataMember(Name="ParentCategoryId", EmitDefaultValue=true)]
        public long? ParentCategoryId { get; set; }

        /// <summary>
        /// The localized name of the category
        /// </summary>
        /// <value>The localized name of the category</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The number of products associated to this category.
        /// </summary>
        /// <value>The number of products associated to this category.</value>
        [DataMember(Name="ProductCount", EmitDefaultValue=false)]
        public int ProductCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CategoryInfoWithProductCountDto {\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  ParentCategoryId: ").Append(ParentCategoryId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProductCount: ").Append(ProductCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CategoryInfoWithProductCountDto)obj);
        }

        /// <summary>
        /// Returns true if CategoryInfoWithProductCountDto instances are equal
        /// </summary>
        /// <param name="other">Instance of CategoryInfoWithProductCountDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CategoryInfoWithProductCountDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CategoryId == other.CategoryId ||
                    
                    CategoryId.Equals(other.CategoryId)
                ) && 
                (
                    ParentCategoryId == other.ParentCategoryId ||
                    ParentCategoryId != null &&
                    ParentCategoryId.Equals(other.ParentCategoryId)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    ProductCount == other.ProductCount ||
                    
                    ProductCount.Equals(other.ProductCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + CategoryId.GetHashCode();
                    if (ParentCategoryId != null)
                    hashCode = hashCode * 59 + ParentCategoryId.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    
                    hashCode = hashCode * 59 + ProductCount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CategoryInfoWithProductCountDto left, CategoryInfoWithProductCountDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CategoryInfoWithProductCountDto left, CategoryInfoWithProductCountDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
