/*
 * TomiSoft Product Database Api
 *
 * This document describes the API provided by the TomiSoft.ProductCatalog.Server microservice. This microservice provides information about products, based on barcode.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: sinkutamas@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using TomiSoft.ProductCatalog.Server.OpenApiGenerated.Converters;

namespace TomiSoft.ProductCatalog.Server.OpenApiGenerated.Models
{ 
    /// <summary>
    /// Provides information about the languages supported by the system
    /// </summary>
    [DataContract]
    public class SystemSupportedLanguagesDto : IEquatable<SystemSupportedLanguagesDto>
    {
        /// <summary>
        /// Contains all the languages supported by the system. By providing one of these languages in Accept-Language header, you can get localized responses
        /// </summary>
        /// <value>Contains all the languages supported by the system. By providing one of these languages in Accept-Language header, you can get localized responses</value>
        [DataMember(Name="SupportedLanguages", EmitDefaultValue=false)]
        public List<string> SupportedLanguages { get; set; }

        /// <summary>
        /// An IETF language tag representing the default language of the system. Used as a fallback value if Accept-Language is not provided in the request or it cannot be fulfilled
        /// </summary>
        /// <value>An IETF language tag representing the default language of the system. Used as a fallback value if Accept-Language is not provided in the request or it cannot be fulfilled</value>
        [DataMember(Name="DefaultLanguage", EmitDefaultValue=false)]
        public string DefaultLanguage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SystemSupportedLanguagesDto {\n");
            sb.Append("  SupportedLanguages: ").Append(SupportedLanguages).Append("\n");
            sb.Append("  DefaultLanguage: ").Append(DefaultLanguage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SystemSupportedLanguagesDto)obj);
        }

        /// <summary>
        /// Returns true if SystemSupportedLanguagesDto instances are equal
        /// </summary>
        /// <param name="other">Instance of SystemSupportedLanguagesDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SystemSupportedLanguagesDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SupportedLanguages == other.SupportedLanguages ||
                    SupportedLanguages != null &&
                    other.SupportedLanguages != null &&
                    SupportedLanguages.SequenceEqual(other.SupportedLanguages)
                ) && 
                (
                    DefaultLanguage == other.DefaultLanguage ||
                    DefaultLanguage != null &&
                    DefaultLanguage.Equals(other.DefaultLanguage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SupportedLanguages != null)
                    hashCode = hashCode * 59 + SupportedLanguages.GetHashCode();
                    if (DefaultLanguage != null)
                    hashCode = hashCode * 59 + DefaultLanguage.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SystemSupportedLanguagesDto left, SystemSupportedLanguagesDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SystemSupportedLanguagesDto left, SystemSupportedLanguagesDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
